# General  
train_2d: False
no_eval: False
finetune: True
partial_train: null

# Traning 
epochs: 120
checkpoint_frequency: 30
batch_size: 24
dropout: 0.0
learning_rate: 0.0002
weight_decay: 0.01
lr_decay: 0.99

# Model
maxlen: 243
dim_feat: 512
mlp_ratio: 2
depth: 5
dim_rep: 512
num_heads: 8
att_fuse: True

# Data
data_root: /nfs/turbo/coe-shdpm/leyang/VEHS_MB/RTM2D_37kpts_VEHS7M/V5_2-b/
subset_list: [pitch_correct]
dt_file: /V5_2-b/pitch_correct/VEHS_6D_downsample5_keep1_37_v2_pitch_correct_modified_RTM2D.pkl
clip_len: 243
data_stride: 81
rootrel: True
sample_stride: 1
num_joints: 37
joint_format: RTM-37
no_conf: False
gt_2d: False
root_idx: 0
res_w: 1920
res_h: 1200

# Loss
lambda_3d_velocity: 20.0
lambda_scale: 0.5
lambda_lv: 0.0  #0.5 --> limb
lambda_lg: 0.0  #0.5  --> limb
lambda_a: 0.0  #0.5  --> angle
lambda_av: 0.0  #0.5 --> angle

# Augmentation
synthetic: False
flip: True
mask_ratio: 0.0
mask_T_ratio: 0.0
noise: False
noise_path: params/synthetic_noise.pth
d2c_params_path: params/d2c_params.pkl